# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "https://nklumiz-mp51299.snowflakecomputing.com"
user = "DUNJA123"
password = "@@Budedobro2"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SNOWFLAKE_SAMPLE_DATA"
schema = "PETROVDU_DTLB"

