# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "nklumiz-mp51299"
user = "DUNJA123"
password = "@@Budedobro2"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "HOL_DB"


